### ISSUE TITLE
update Gemfile for latest ruby

### ISSUE THREAD

**Issue by ghost** [francoisledroff/connectcon-chef-repo#2]
/Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/mixlib-authentication-1.3.0/lib/mixlib/authentication/signedheaderauth.rb:94:in `private_encrypt': private key needed. (OpenSSL::PKey::RSAError)
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/mixlib-authentication-1.3.0/lib/mixlib/authentication/signedheaderauth.rb:94:in`sign'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley/middleware/chef_auth.rb:22:in `authentication_headers'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley/middleware/chef_auth.rb:66:in`call'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/request/retry.rb:87:in `call'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in`build_response'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley/connection.rb:104:in`run_request'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in`public_send'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in`dispatch'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in`block in task'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in`block in initialize'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/thread_handle.rb:13:in`block in initialize'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/actor_system.rb:32:in `block in get_thread'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/internal_pool.rb:99:in`call'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/internal_pool.rb:99:in `block in create'
    from (celluloid):0:in`remote procedure call'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:92:in `value'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/sync_proxy.rb:33:in`method_missing'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/pool_manager.rb:41:in`_send_'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/pool_manager.rb:123:in `method_missing'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in`public_send'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in`dispatch'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in`block in task'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in`block in initialize'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    from (celluloid):0:in`remote procedure call'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:92:in `value'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/sync_proxy.rb:33:in`method_missing'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley/resource.rb:132:in `raw_request'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley/resource.rb:123:in`request'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley/resources/cookbook_resource.rb:94:in `find'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley/resources/cookbook_resource.rb:188:in`upload'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in`dispatch'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in`block in invoke'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in`block in task'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_thread.rb:21:in`block in create'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/thread_handle.rb:13:in `block in initialize'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/actor_system.rb:32:in`block in get_thread'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/internal_pool.rb:99:in `call'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/internal_pool.rb:99:in`block in create'
    from (celluloid):0:in `remote procedure call'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:92:in`value'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/uploader.rb:54:in`block (2 levels) in upload'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/uploader.rb:50:in `each'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/uploader.rb:50:in`block in upload'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley/client.rb:36:in `open'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/ridley-4.0.0/lib/ridley.rb:51:in`open'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf.rb:157:in `ridley_connection'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/uploader.rb:49:in`upload'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/uploader.rb:36:in `run'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/berksfile.rb:542:in`upload'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:208:in `upload'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:52:in `dispatch'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/lib/berkshelf/cli.rb:27:in `execute!'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/gems/berkshelf-3.1.3/bin/berks:5:in`<top (required)>'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/bin/berks:23:in `load'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/bin/berks:23:in`<main>'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
    from /Users/npeltier/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in`<main>'

**Comment by ghost** [comment]
@francoisledroff doesn't seems to be related to ruby versiojn

**Comment by ghost** [comment]
/Users/npeltier/.rvm/gems/ruby-2.1.2/gems/mixlib-authentication-1.3.0/lib/mixlib/authentication/signedheaderauth.rb:94:in `private_encrypt': private key needed. (OpenSSL::PKey::RSAError)
    from /Users/npeltier/.rvm/gems/ruby-2.1.2/gems/mixlib-authentication-1.3.0/lib/mixlib/authentication/signedheaderauth.rb:94:in`sign'
    from /Users/npeltier/.rvm/gems/ruby-2.1.2/gems/ridley-4.0.0/lib/ridley/middleware/chef_auth.rb:22:in `authentication_headers'
    from /Users/npeltier/.rvm/gems/ruby-2.1.2/gems/ridley-4.0.0/lib/ridley/middleware/chef_auth.rb:66:in`call'
    from /Users/npeltier/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/request/retry.rb:87:in `call'
    from /Users/npeltier/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in`build_response'
    from /Users/npeltier/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /Users/npeltier/.rvm/gems/ruby-2.1.2/gems/ridley-4.0.0/lib/ridley/connection.rb:104:in`run_request'
    from /Users/npeltier/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'

**Comment by ghost** [comment]
some mess up with my private key
